services:
  - type: web
    name: lapnomba-backend
    env: node
    plan: free
    rootDir: api        
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DB_PROTOCOL
        value: postgres
      - key: DB_HOST
        value: lapnomba-db
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: password
      - key: SALT_ROUNDS
        value: "10"
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: ADMIN_EMAIL
        value: admin@lapnomba.org
      - key: ADMIN_PASSWORD
        value: admin