services:
  - type: web
    name: lapnomba-backend
    env: node
    plan: free
    rootDir: api        
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080