apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-backend
  labels:
    app: marketplace-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: marketplace-backend
  template:
    metadata:
      labels:
        app: marketplace-backend
    spec:
      containers:
        - name: marketplace-backend
          image: your-docker-image:latest
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: url
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"