apiVersion: v1
kind: Service
metadata:
  name: lapnomba-backend-service
spec:
  type: LoadBalancer
  selector:
    app: lapnomba-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
