apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
  labels:
    app: marketplace
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: marketplace